apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "task-tracker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "task-tracker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "task-tracker.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "task-tracker.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: task-tracker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "task-tracker.fullname" . }}-config
          ports:
            - name: http
              containerPort: {{ .Values.env.port }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
